# tmux list-windows
#    layout: b147,208x73,0,0[208x62,0,0,208x10,0,63{104x10,0,63,103x10,105,63}]

windows:
  - main:
      layout: main-horizontal
      panes:
        - #default
  - stock:
      layout: even-vertical
      panes:
        - vim /tmp/file
        - cd /opt/directory
  - status:
      layout: main-horizontal
      panes:
        - htop
  - test:
      layout: tiled
      pre:
        - echo 'test 1'
        - echo 'test 2'
      panes:
        -
        -
        -
