#!/bin/bash

if [ `whoami` != root ]; then
    echo Please run this script as root or using sudo
    exit
fi

# apt-get install -f

silversearcher-ag expect git tmux gparted gdisk htop ssh vsftpd samba vim filezilla nautilus-dropbox bind9 supervisor vim vnc4server vncpasswd nodejs npm nginx
redis-server cpulimit autojump

### Latest per website instructions ###
mongodb
docker (docker-engine)
mono (mono-devel, mono-complete)
monodevelop
oh-my-zsh

# stop ssh and other attacks
apt-get install fail2ban
# apt-get install denyhosts

# node verse nodjs
ln -s /usr/bin/nodejs /usr/bin/node

### NPM installs ###
npm install bower -g
npm install gulp -g

# http://rvm.io/
curl -sSL https://get.rvm.io | bash -s stable

# https://github.com/tmuxinator/tmuxinator
gem install tmuxinator

# https://github.com/gmarik/Vundle.vim
git clone https://github.com/gmarik/vundle.git ~/.vim/bundle/vundle

# terminal landscape systeminformation
apt-get install landscape-client
