#!/bin/bash

# Usage: <-r> <host> <username> <password>

_command=$1
_host=$2
_port=23
_username=$3
_password=$4

if [[ $_command == -r ]]; then
  ( echo open ${_host} ${_port}
    sleep 1
    echo ${_username}
    sleep 1
    echo -e "\r"
    sleep 1
    echo ${_password}
    sleep 1
    echo -e "\r"
    sleep 3
    echo "enable"
    sleep 1
    echo -e "\r"
    sleep 1
    echo "admin"
    sleep 1
    echo -e "\r"
    sleep 3
    echo "sys reboot"
    sleep 1
    echo -e "\r"
    sleep 1
    echo -e "y\r"
    sleep 1
    echo exit ) | telnet
fi
